#!/bin/bash

#################################################################
#---------------------SET ALL VARIABLES-------------------------#
#################################################################

backupDirectory='/mnt/lightning/backup/paperless/'
eyeheartpie='/mnt/disks/eyeheartpie-ssh-secure/paperless/'
#rebootlabs='/mnt/disks/eyeheartpie-ssh-secure/paperless/'

#################################################################
#---------------------COPY TO REMOTE 1--------------------------#
#################################################################

  rclone sync -v \
  --fast-list \
  --tpslimit=10 \
  --checkers=4 \
  --transfers=2 \
  ""$backupDirectory""/ eyeheartpie-ssh-secure:paperless
  
#################################################################
#---------------------COPY TO REMOTE 2--------------------------#
#################################################################

#  rclone sync -v \
#  --fast-list \
#  --tpslimit=10 \
#  --checkers=4 \
#  --transfers=2 \
#  ""$backupDirectory""/ reboot-ssh-secure:paperless

#################################################################
#---------------------------------END---------------------------#
#################################################################
